### ISSUE TITLE
Enhancement Request: Which Hidden Detour to activate first?

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1007]
**Describe the bug**
When 2 or more copies of Gyrosaur's Hidden Detour are in play, and an environment card is about to enter play, the user is not prompted as to which Hidden Detour should activate first. The user has to Meanwhile... back to their play area and check the Hidden Detours to see which they want to use, if at all. 

**What does it affect**
Card(s): Hidden Detour
Deck(s): Gyrosaur

**Expected behavior**
"Which of these cards (shows both Hidden Detours) should activate first?"

**Comment by cdallasanta** [comment]
<img width="1024" alt="HiddenDetour" src="https://user-images.githubusercontent.com/42685426/113382646-e128da00-9336-11eb-9e3c-a81c747a8093.png">
Image of current behavior with 2 Hidden Detours in play. They trigger one at a time in play order, which is according to the game rules. One possible approach would be to display the "Hidden" card instead of "Hidden Detour," but then it obfuscates why the player is making the decision.

**Comment by mredgecase** [comment]
Could two special strings be added, then?
1. There [is/are] [one/two] Hidden Detour[s] in play. 
2. [x] is under Hidden Detour; [y] is under Hidden Detour.
