### ISSUE TITLE
Enhancement Request: Special String tune-up for Sig-Quil's Sign

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1025]
At present, Sig-Quil's Sign's special string displays "increase damage dealt by 1" in the effects menu twice. 

I think it would be preferable to have it specify: 

- increase damage dealt to targets in [Character's] deck by 1
- increase damage dealt by targets from [Character's] deck by 1

![image](https://user-images.githubusercontent.com/78523123/109583753-6a49b880-7ace-11eb-9e51-021596f99d8a.png)

**Comment by wrhyme29** [comment]
This is an engine limitation. We can't control what this special string says, so even though its coded identical to TN AZ aside from affecting all targets for the deck instead of just the character card, we can't get it to show that.

Leaving open for if Handelabra gives us a way to have more control over things like this.

**Comment by wrhyme29** [comment]
I figured out how to do this to make it much more meaningful - look for this enhancement in the next update.
