### ISSUE TITLE
Infernal Chorus- odd text on villain card + unnecessary multiple form box

### ISSUE THREAD

**Issue by JeffP1976** [SotMSteamMods/CauldronMods#1154]
**Describe the bug**

When playing a game vs. Infernal Chorus- I double clicked the villain card to check her text. She had flipped and the card's text was obscured by words (see below). The words were only consistently there if I clicked on the villain card, but only the back side. 
Also she has a clickable box for multiple forms- like Skyscraper- when I clicked the box, the odd text disappeared and the "form" button dissapeared- see image 2 and 3

Odd text:
![Capture 1](https://user-images.githubusercontent.com/81578253/112863680-1908f680-9085-11eb-8d7d-1a12f0052726.JPG)

The strange button:
![Capture 2](https://user-images.githubusercontent.com/81578253/112864491-dbf13400-9085-11eb-9afe-03638a0116a2.JPG)

After the button is pressed:
![Capture 3](https://user-images.githubusercontent.com/81578253/112865977-4eaedf00-9087-11eb-9504-6de50aa6d1e4.JPG)

**What does it affect**
Card(s): Infernal Chorus villain card

**To Reproduce**
Looks like any battle with Infernal Chorus

**Comment by wrhyme29** [comment]
I'm unable to replicate this issue in either tests or in game unfortunately. If you still have the Output.log, I could try to track down more specifically what was going on in this situation. This almost always is because of Special Strings, but those all look fine to me.

Closing this issue for now.
