### ISSUE TITLE
Whetstone goes into play next to The Knight but it does not say that it should.

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1279]
**Describe the bug**
Whetstone goes into play next to The Knight but it does not say that it should. Same for Stalward Shield and Platemail and Plate helm and maybe more.

**What does it affect**
Card(s):Various
Deck(s):The Knight

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

Play the cards.

**Expected behavior**
The cards go into play into the Knight's play area, not next to any card.

See #1272 for attachments.

**Comment by wrhyme29** [comment]
(Commenting for my own sake): This is happening because their is a variant with multiple character cards which has you play all equipment next to one of the two. In Oblivaeon, likely the other incapped heroes in the same zone as the Knight are causing that check for multiple character cards to pass, resulting in them being played next to the Knight.
