### ISSUE TITLE
Corpse Explosion says it hits all villain targets but it doesn’t hit The Red Menace

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1377]
**Describe the bug**
Corpse Explosion triggered, but did not deal damage to The Red Menace (OblivAeon objective), who is a villain target.

**What does it affect**
Card(s):Corpse Explosion
Deck(s):Necro

Happened on this stream:
https://www.twitch.tv/videos/1057419969

**Comment by wrhyme29** [comment]
Just a note for me later today:

This is because it is separately checking for "isVillain" and "isTarget" and Red Menace returns false to "isVillain" but true to "isVillainTarget". The reason for the separate checks was for the variant that flips the "hero" and "villain" keyword for all his cards to be able to swap the "isVillain" to an "isHero" check. 

The likely solution to this is to move the "isTarget" check into function that returns "isHero" or "isVillain" instead returning "isVillainTarget" or "isHero && isTarget"
