### ISSUE TITLE
Using Pyre's Cherenkov drive on Benchmark's Auto-Targeting Protocol only hits one target

### ISSUE THREAD

**Issue by Omegatron9** [SotMSteamMods/CauldronMods#1405]
**Describe the bug**
When Pyre uses Cherenkov Drive to irradiate Benchmark's Auto-Targeting protocol and let Benchmark use the power on it, it only lets Benchmark hit one target

**What does it affect**
Card(s): Cherenkov Drive, Auto-Targeting Protocol
Deck(s): Pyre, Benchmark

**To reproduce**
1. As Pyre, play Cherenkov Drive
2. At then end of Pyre's turn select Benchmark and irradiate Auto-Targeting Protocol
3. Choose to use the power on Auto-Targeting Protocol
4. Deal damage to one target
5. After damage is dealt to that target, the game continues without the target selection UI coming back to let you select more targets.

**Expected behaviour**
After dealing damage to the first target, the target selection UI should re-appear to let me select more targets to damage, like when you use the power on Auto-Targeting Protocol directly

I don't know if this also affects other multi-target powers, I haven't tested those. Log file is attached in case it helps.

[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6801039/log.txt)

**Comment by wrhyme29** [comment]
This is known behavior. When you use Cherenkov drive it will only perform the first part of any power. In the case of Auto Targeting Protocol, that is hitting the first target. This is because the card is in the discard when it is being activated,, which normally prevents all actions. While we can create an exception for the initial action, we cannot create those exceptions for subsequent actions. At this time, there is nothing we can do about it. 

I'm closing this because this same behavior is documented in other issues.
