### ISSUE TITLE
Tango One - Chameleon Armor incorrect prompt text

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#141]
**Describe the bug**
The Y/N prompt text when Chameleon Armor tries to trigger is incorrectly "Do you want to discard Chameleon Armor?".  
Critical Hit is using the placeholder "Yes or No?", which is at least not misleading.

**What does it affect**
Card(s): Chameleon Armor
Deck(s): Tango One

**To Reproduce**
1. Play Chameleon Armor
2. Initiate damage to Tango One
3. Read the text of the y/n prompt

**Expected behavior**
The Y/N prompt text should be "Do you want to discard the top card of Tango One's deck?"

**Screenshots**

**Additional context**
This looks like a text error, so should be separate from the more significant Trigger.Before issue with the card.

**Comment by wrhyme29** [comment]
This text is based on the SelectionType of the card, and for the appropriate selection type for chameleon armor, it shows that text (Which is obviously not correct) That is also why Critical Hit shows Y/N alone, because there is no associated text. I can switch it to a Y/N by changing it to a different SelectionType, but I can't change that text
