### ISSUE TITLE
Cherenkhov Drive does not allow powers to hit multiple targets

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1413]
**Describe the bug**
For Cherenkhov Drive, I selected Containment Breach. The card was irradiated, and I chose to use its power to deal Pyre and each non-hero target 1 energy damage. Pyre hit himself, and it gave me a "select the first target" choice, but it will only hit one target from that choice. Whether I hit "choose for me" or select a specific target, the damage ends after one target is hit.  I also noticed the same behavior earlier in the game with Jailbreaker.

**What does it affect**
Card(s): Cherenkhov Drive
Deck(s): Pyre

**To Reproduce**
1. Play as Pyre, and make sure there are multiple non-hero targets
2. Have Cherenkhov Drive in play and a non-irradiated Containment Breach in your hand
3. At the end of your turn, select the non-irradiated Containment Breach

**Expected behavior**
The power should deal damage to all non-hero targets, even when used via Cherenkhov Drive

**Logs**
[Player.log](https://github.com/SotMSteamMods/CauldronMods/files/6874659/Player.log)

**Comment by origamiswami** [comment]
This just happened with Hull Cladding too. It let me draw 1 card, then discarded Hull Cladding

**Comment by wrhyme29** [comment]
This is the same problem as #980 - this is an engine limitation we don't currently have a workaround for. Essentially, we can exempt the very first action for the card in the discard (in this case the first target's damage), but any further actions get prevented since the card is in the discard. Since its the same issue as before I will be closing this as Engine Limitation

**Comment by wrhyme29** [comment]
Just to note - the engine now allows this behavior, so everything for multi-hit as described in this issue works as expected
