### ISSUE TITLE
Tango One - Critical Hit and the damage calculation screen

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#151]
**Describe the bug**
When Critical Hit discards a critical card to add +3 damage to a hit, that +3 is not showing up in the damage calculation screen.

**To Reproduce**
1. Play Critical Hit as Tango One.
2. Attack something and choose to discard from the deck.
3. Have the discarded card randomly be a critical.
4. Watch the numbers on the damage calculation screen.

**Expected behavior**
The bonus from Critical Hit should show up in the damage calculation screen, and the total damage shown after all bonuses should include that bonus.

**Additional context**
I'm pretty sure this is just a display issue and the bonus is being correctly applied.

**Comment by Vilnor** [comment]
This is a known issue from initial development on TangoOne.  Thank you for opening a issue for it.

**Comment by qoala** [comment]
Possibly related issue (I haven't learned enough about the code to know if this preview is a separate code path):

In the damage preview when Tango One is selecting a target (where it shows the damage modifiers that may take effect if that target were chosen), Critical Hit is listed with the damage prevented icon instead of a +3 or a "?" as the effect.
