### ISSUE TITLE
Special string exception with Possessor in OA mode

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1557]
**Describe the bug**
When Possessor is next to a hero in the other battle zone from St Simeons, its special string has an exception.

**What does it affect**
Card(s): Possessor
Deck(s): St Simeons

`InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.First[Card] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at Cauldron.StSimeonsCatacombs.StSimeonsGhostCardController.BuildAffectedCardString () [0x00000] in <filename unknown>:0 
  at Cauldron.StSimeonsCatacombs.StSimeonsGhostCardController.<.ctor>b__0_0 () [0x00000] in <filename unknown>:0 
  at Handelabra.Sentinels.View.UIEffectListPanel.ShowForCard (Handelabra.Sentinels.Engine.Model.Card card) [0x00000] in <filename unknown>:0 `

![Screen Shot 2022-01-25 at 10 36 46 PM](https://user-images.githubusercontent.com/345012/151195907-4354e079-f0ca-4757-b9fb-fec4377ef37f.jpg)

[save-undo-232-OblivAeon-Start.dat.zip](https://github.com/SotMSteamMods/CauldronMods/files/7943052/save-undo-232-OblivAeon-Start.dat.zip)

**Comment by wrhyme29** [comment]
Still looking at the actual issue, but I thought I'd let you know the following as an FYI:

When I load up the save file and start replaying it, it can't find any of the Mission Cards, and it stops after one hero's turn without ever reaching St Simeons:

Test Name:	TestIssue1557
Test Outcome:	Passed
Result StandardOutput:	
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:TheLastWager
WARNING: CardDefinition not found in OblivAeon decklist for promo card: TheLastWager
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:CitizenStorm
WARNING: CardDefinition not found in OblivAeon decklist for promo card: CitizenStorm
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:ShatteringBlow
WARNING: CardDefinition not found in OblivAeon decklist for promo card: ShatteringBlow
DEBUG: LoadDefinitionOverridingTurnTaker looking for Stuntman:ActionHeroStuntmanCharacter
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:GreatFortune
WARNING: CardDefinition not found in OblivAeon decklist for promo card: GreatFortune
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:OrchestrateTheVoid
WARNING: CardDefinition not found in OblivAeon decklist for promo card: OrchestrateTheVoid
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:SummonTheColosseum
WARNING: CardDefinition not found in OblivAeon decklist for promo card: SummonTheColosseum
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:HermeticEvolved
WARNING: CardDefinition not found in OblivAeon decklist for promo card: HermeticEvolved
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:BuildingAKing
WARNING: CardDefinition not found in OblivAeon decklist for promo card: BuildingAKing
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:TheNationsInRuins
WARNING: CardDefinition not found in OblivAeon decklist for promo card: TheNationsInRuins
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:TheDigitalAge
WARNING: CardDefinition not found in OblivAeon decklist for promo card: TheDigitalAge
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:TheFinalChampion
WARNING: CardDefinition not found in OblivAeon decklist for promo card: TheFinalChampion
DEBUG: LoadDefinitionOverridingTurnTaker looking for OblivAeon:Hellion
WARNING: CardDefinition not found in OblivAeon decklist for promo card: Hellion
# of saved replay decision answers: 542
Successfully created game to replay...
========================== START GAME ==========================
DEBUG: GameController puts The Arc of Unreality into play.
DEBUG: The Arc of Unreality moved Progeny from OblivAeon's off to the side to the First Battle Zone Scion play area.
DEBUG: GameController moves 4 cards cards to the top of OblivAeon's OutOfGame.
DEBUG: GameController puts The Scion Reserve into play.
DEBUG: GameController moves 9 cards cards to the top of The Scion Reserve's UnderCard.
DEBUG: GameController moved Faultless from under The Scion Reserve to the Second Battle Zone Scion play area.
DEBUG: GameController puts Inevitable Destruction Card into play.
DEBUG: GameController plays Aeon Locus.
DEBUG: GameController moved Aeon Locus from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: GameController plays Aeon Vassal.
DEBUG: GameController moved Aeon Vassal from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: GameController plays Aeon Thrall.
DEBUG: GameController moved Aeon Thrall from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: GameController plays Aeon Locus.
DEBUG: GameController moved Aeon Locus from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: GameController plays Aeon Locus.
DEBUG: GameController moved Aeon Locus from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: Turned to the next page in the OblivAeon booklet.
DEBUG: St. Simeon's Catacombs Instructions puts St. Simeon's Catacombs Instructions into play.
DEBUG: Instructions card did enter play.
DEBUG: NOTE: GameController is not cancelled by St. Simeon's Catacombs Instructions because the card says 'put into play' rather than 'play card'.
DEBUG: GameController puts St. Simeon's Catacombs into play.
DEBUG: St. Simeon's Catacombs moves 5 cards cards to the top of St. Simeon's Catacombs's UnderCard.
DEBUG: St. Simeon's Catacombs shuffles their under St. Simeon's Catacombs.
DEBUG: Went to OblivAeon's BeforeStart phase.
DEBUG: Went from OblivAeon's BeforeStart phase to Start phase. 
DEBUG: OblivAeon removes 1 token from The Countdown.
DEBUG: Went from OblivAeon's Start phase to PlayCard phase. 
DEBUG: GameController plays Temporal Fractures.
DEBUG: Temporal Fractures removes 1 token from The Countdown.
DEBUG: Created decision [SelectTargets/None D1]
DEBUG: Created decision [SelectTarget/None D1-1]
MakeDecisions: [SelectTarget/SelectTarget D1-1]
DEBUG: Writhe: Cosmic Inventor initiates 2 Energy damage to Magnificent Mara.
DEBUG: Writhe: Cosmic Inventor deals Magnificent Mara 2 Energy damage.
DEBUG: Magnificent Mara is now at 25 HP.
DEBUG: Created decision [SelectTarget/None D1-2]
DEBUG: Writhe: Cosmic Inventor initiates 2 Energy damage to K.N.Y.F.E. Rogue Agent.
DEBUG: Writhe: Cosmic Inventor deals K.N.Y.F.E. Rogue Agent 2 Energy damage.
DEBUG: K.N.Y.F.E. Rogue Agent is now at 27 HP.
DEBUG: Created decision [SelectTarget/None D1-3]
DEBUG: Writhe: Cosmic Inventor initiates 2 Energy damage to Absolute Zero.
DEBUG: Writhe: Cosmic Inventor deals Absolute Zero 2 Energy damage.
DEBUG: Absolute Zero is now at 27 HP.
DEBUG: Created decision [SelectTarget/None D1-4]
DEBUG: Writhe: Cosmic Inventor initiates 2 Energy damage to Heroic Luminary.
DEBUG: Writhe: Cosmic Inventor deals Heroic Luminary 2 Energy damage.
DEBUG: Heroic Luminary is now at 26 HP.
DEBUG: Created decision [SelectTarget/None D1-5]
DEBUG: Magnificent Mara moved from the First Battle Zone to the Second Battle Zone.
DEBUG: K.N.Y.F.E. Rogue Agent moved from the First Battle Zone to the Second Battle Zone.
DEBUG: Absolute Zero moved from the First Battle Zone to the Second Battle Zone.
DEBUG: Heroic Luminary moved from the First Battle Zone to the Second Battle Zone.
DEBUG: GameController moved Temporal Fractures to OblivAeon's trash.
DEBUG: Went from OblivAeon's PlayCard phase to End phase. 
Message: OblivAeon plays the 3 top cards of The Aeon Men Deck. [ OblivAeon ]
DEBUG: OblivAeon plays Aeon Vassal.
DEBUG: GameController moved Aeon Vassal from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: OblivAeon plays Aeon Thrall.
DEBUG: GameController moved Aeon Thrall from The Aeon Men Deck to the Second Battle Zone Scion play area.
DEBUG: OblivAeon plays Aeon Thrall.
DEBUG: GameController moved Aeon Thrall from The Aeon Men Deck to the Second Battle Zone Scion play area.
Message: There are no aeon men cards for OblivAeon to destroy. [ OblivAeon ]
DEBUG: OblivAeon adds 1 token to Devastation Token Pool.
DEBUG: OblivAeon adds 2 tokens to Devastation Token Pool.
Message: OblivAeon plays the top card of The Aeon Men Deck. [ OblivAeon ]
DEBUG: OblivAeon plays Aeon Warrior.
DEBUG: GameController moved Aeon Warrior from The Aeon Men Deck to the First Battle Zone Scion play area.
DEBUG: Went from OblivAeon's End phase to AfterEnd phase. 
DEBUG: Went from OblivAeon's AfterEnd phase to Magnificent Mara's BeforeStart phase. 
DEBUG: Created decision [YesNo/None D2 Magnificent Mara]
MakeDecisions: [YesNo/SwitchBattleZone D2 Magnificent Mara]
DEBUG: Created decision [SelectFunction/SelectFunction D3 Magnificent Mara]
MakeDecisions: [SelectFunction/SelectFunction D3 Magnificent Mara]
DEBUG: GameController puts The Last Wager into play.
DEBUG: GameController moved The Last Wager from The Mission Deck to Magnificent Mara's play area.
DEBUG: Went from Magnificent Mara's BeforeStart phase to Start phase. 
DEBUG: Went from Magnificent Mara's Start phase to PlayCard phase. 
DEBUG: Created decision [SelectCard/None D4 Magnificent Mara]
MakeDecisions: [SelectCard/PlayCard D4 Magnificent Mara]
DEBUG: GameController plays Mix it up.
Message: There are no cards in play for Mix it up to destroy. [  ]
DEBUG: GameController moved Mix it up to Magnificent Mara's trash.
DEBUG: Went from Magnificent Mara's PlayCard phase to UsePower phase. 
DEBUG: Created decision [UsePower/UsePower D5 Magnificent Mara]
MakeDecisions: [UsePower/UsePower D5 Magnificent Mara]
DEBUG: Magnificent Mara uses the power on Magnificent Mara.
DEBUG: Created decision [SelectTargets/None D6 Magnificent Mara]
DEBUG: Created decision [SelectTarget/None D6-1 Magnificent Mara]
MakeDecisions: [SelectTarget/SelectTarget D6-1 Magnificent Mara]
WARNING: ReplayDecisionAnswers did not have an entry for this decision: [SelectCardDecision, ID=6-1, Hero=Magnificent Mara, SelectionType=SelectTarget, IsOptional=False, CardSource=[CardSource: ID=30843, CardController=Magnificent Mara], SelectedCard=]
[Magnificent Mara] Magnificent Mara, Make a SelectCardDecision of type SelectTarget: [Magnificent Mara, K.N.Y.F.E. Rogue Agent, Absolute Zero, Heroic Luminary, Faultless, Aeon Locus, Aeon Vassal, Aeon Thrall, Aeon Locus, Aeon Locus, Aeon Vassal, Aeon Thrall, Aeon Thrall])
--- BEGIN PREVIEW ---
Selected Target: Aeon Locus
Final Result: Magnificent Mara deals 1 Psychic damage to Aeon Locus.
--- END PREVIEW ---
Selected: Aeon Locus
DEBUG: Magnificent Mara initiates 1 Psychic damage to Aeon Locus.
DEBUG: Magnificent Mara deals Aeon Locus 1 Psychic damage.
DEBUG: Aeon Locus is now at 5 HP.
DEBUG: Created decision [SelectTargets/None D7 Magnificent Mara]
DEBUG: Created decision [SelectTarget/None D7-1 Magnificent Mara]
MakeDecisions: [SelectTarget/SelectTarget D7-1 Magnificent Mara]
DEBUG: Aeon Locus initiates 1 Melee damage to Aeon Thrall.
DEBUG: Aeon Locus deals Aeon Thrall 1 Melee damage.
DEBUG: Aeon Thrall is now at 3 HP.
DEBUG: Went from Magnificent Mara's UsePower phase to DrawCard phase.
