### ISSUE TITLE
Nobility of Dusk needs better Yes or No prompt

### ISSUE THREAD

**Issue by TheLastTrueBlade** [SotMSteamMods/CauldronMods#423]
**Describe the bug**
Nobility of Dusk asks Yes or No, but not why

**What does it affect**
Card(s): Nobility of Dusk
Deck(s): Lady of the Wood

**To Reproduce**
1) Have Nobility of Dusk in play. 
2) Have LotW do damage.

**Expected behavior**
It should ask "Do you want to increase damage by 2?" instead of "Yes or No?"

**Screenshots**
![20201205203320_1](https://user-images.githubusercontent.com/75555294/101271631-68739180-3739-11eb-8f41-b06cf868587a.jpg)

**Additional context**

**Comment by wrhyme29** [comment]
This is a limitation of the engine currently. This text comes from the SelectionType of the decision, and Handelabra only has special text for things that they needed to use. 

This Yes/No is the best we can do at this time.

MigrantP's response on the matter:

"Not at this time, the display of text for decisions is determined by the UI
Though with mods doing whatever they want, seems likely we'll want to add support for the engine sending strings for that
(it's more complicated than just one string due to multiplayer)"

**Comment by TheLastTrueBlade** [comment]
Got it
