### ISSUE TITLE
Titan - Titanform

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#472]
**Describe the bug**
If Titanform's damage reduction is triggered by Titan taking damage, it doesn't go away if Titanform is destroyed. Instead it goes away at the start of Titan's turn like it was still in play.

**What does it affect**
Card(s): Titanform
Deck(s): Titan

**To Reproduce**
1. Have Titanform in play.
2. Deal damage to Titan to trigger the damage reduction effect.
3. Destroy Titanform.
4. See that the damage reduction effect is still being applied.

**Expected behavior**
When Titanform is destroyed, it's corresponding damage reduction(s) go away.

**Screenshots**
None at the moment, will try to get one.

**Comment by LNBertolini** [comment]
This is intentional. At least, it was intentionally coded to work this way.

Consider the text of the card. "Whenever {Titan} is dealt damage by another target, reduce damage dealt to {Titan} by 1 until the start of your next turn." That's describing a trigger that 1) reacts when Titan gets hit and 2) sets up an ongoing status effect. Those are, by default, not tied to whether a card is still in play. (Compare to, say, Mr. Fixer's Hoist Chain - "Whenever {MrFixer} deals Damage to a Target, reduce all Damage dealt by that Target by 1 until the start of your next turn." - whose effect also continues applying after it leaves play.)

If it were to have the effect you ask for, the wording would probably be pretty awkward - either have an "if Titanform is in play"  rider somewhere, or be completely different. "Reduce damage dealt to Titan by 1 for each time he has been dealt damage by another target since the start of your last turn," I think.

Unless we get word from tosx that we're misrepresenting the intended effect, no change is needed.
