### ISSUE TITLE
Smoke and Mirrors is a lot of...well, smoke and mirrors. 

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#541]
**Describe the bug**
Smoke and Mirrors, when destroyed to prevent a target from taking damage, isn't preventing said damage.

**What does it affect**
Card(s): Smoke and Mirrors
Deck(s): Magnificent Mara

**To Reproduce**
1. Voss vs Renegade Cricket, FS Parse, LOTW 2199, Mara, and Akash in Champion Studios
2. Voss had Vyktor in play, Mara had Smoke and Mirrors and Improbable Escape
3. Voss deals out his end of turn damage, Mara sacrifices Smoke and Mirrors to "prevent" either instance, neither worked. 

**Expected behavior**
The damage to be prevented.

**Screenshots**

**Additional context**

**Comment by LNBertolini** [comment]
I can't get this to happen, or at least your description doesn't give enough details for me to replicate it. If you had two copies of Smoke and Mirrors out, this may be related to [a bug](https://github.com/SotMSteamMods/CauldronMods/issues/515) in the pre-release version that should be fixed in the actual release.

**Comment by TheRealTails** [comment]
There weren't two in play, I'm afraid.

**Comment by LNBertolini** [comment]
I think I may have figure out what the issue was - it's long enough ago that I'm not surprised if you can't remember, but did Cricket have Acoustic Distortion in play?
