### ISSUE TITLE
Starlight - Pillars of Creation, when skipping play phase

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#721]
**Describe the bug**
When Starlight's player skips their play phase, Pillars of Creation ("at the start of your play phase") shouldn't trigger.

**What does it affect**
Card(s): Pillars of Creation, Need a Way Out, Time Crawls
Deck(s): Starlight, Echelon, Realm of Discord

**To Reproduce**
1. Starlight has Pillars of Creation in play and a Constellation in trash
2. Echelon has Need a Way Out in play
3. At the start of Starlight's turn, choose to skip your play phase for Need a Way Out
4. See Pillars of Creation play a Constellation from trash.

**Expected behavior**
Pillars of Creation doesn't trigger if Starlight's play phase was skipped.

**Screenshots**

**Logs**

**Additional context**
Built at 2fe4107b51

---

The vanilla implementation of Time Crawls is likely incompatible with Pillars of Creation. When entering the power phase, it checks to see if a card was played during the play phase, and if so, skips the power phase. This just enters the play phase and effectively considers it skipped if the player chooses the "skip" action in the UI.
(In case something has messed with the phase order, it also does a similar check to skip the play phase if a power was used during the power phase. This case hopefully behaves similar to Need a Way Out once that is working. Wager Master can reverse the phase order, and when hit with ongoing destruction can allow multiples of the same phase within a single turn. Incapped Fugue State Parse or La Comodora allow play/power/draw to occur in arbitrary order)

Best guess for Time Crawls is to do a hard-coded check for Time Crawls in play, and add a yes/no choice at the start of the play phase if so (once regardless of the number of Pillars of Creation in play). If "yes", then skip the rest of the phase. If "no", we'd still need to ensure that Time Crawls understands that the play phase has occurred (faking a journal entry? maybe just skip the power phase ourselves?)
Additional complexity would also be needed to make sure this behaves correctly (doesn't allow incorrectly skipping the play phase if the power phase has already occurred).

**Comment by qoala** [comment]
QuagmaBlast noted in the discord that Pillars of Creation is currently implemented as "end of Start of Turn", because the engine automatically skips the play phase if there are no playable cards.

Leaving this to track the various edge cases that this workaround leaves.

**Comment by MSpekkio** [comment]
Engine wise, the No Cards in Hand, slip play Phase logic can't be overridden.  See GameController.cs around line 2432.  And unfortunately, the PhaseChangeAction event then never raised.  We might be able to narrow the gap a bit by only having the 'early' trigger' if we know there's no cards in hand, and using a Play Phase, Before trigger otherwise.

**Comment by MSpekkio** [comment]
I've added tests specifically for Echelon's Need A Way Out, WagerMasters's Breaking the Rules, Realm of Discords Time Crawls, and a few general conditions.

Need a Way Out will skip the Constellation play while still working for the other cases. 

Note that Time Crawls works preventing the UsePower IF the hero played any cards during the play phase, and since Pillar's play isn't optional, it correctly plays a card and forces the player to skip the power phase.
